### ISSUE TITLE
Doesn't seem to parse PowerNex build file

### ISSUE THREAD

**Issue by marler8997** [Vild/Wild#4]
It looks like Wild is not recognizing ':' as a token...I looked at the lexer and didn't see any code that would recognize that character.  Is this expected?

**Comment by Vild** [comment]
I'm currently in the middle of rewriting the file frontend to use a custom format instead of json, I think that 3a618d4464c192e330868612ec77cd6f8cd8098c should work, it's the last one before the start of the rewrite

**Comment by marler8997** [comment]
Ok cool.  Hey if you want help with something let me know, maybe I can find time.  Writing an OS in D is too cool to not offer a helping hand.  I don't know if you'd want help in the front end or not, but if you had a spec I'd be willing to implement it.  But I understand if you want to do it on your own, I myself am very picky when it comes to code.
